# Schema for Dedupe's tables:
schema: dedupeproject
# The source table to dedupe:
table: PROJECT_ISTAR
# The column in the source table that is the key
key: MasterID
# The fields to use as evidence of a duplicate row and their comparison operator:
fields:
    -   field: Title
        type: String
        has missing: true
# Turn off interactive labeling; this requires a saved training set
prompt_for_labels: True
# You can manually tune the desired recall for the training labels. This
# establishes a blocking pattern such that at least `recall` fraction of the
# true labeled matches get blocked together.
recall: 0.99
# Specify the location of the saved training dataset
training_file: dedup_project_training.json
settings_file: dedup_project_setting
# You may optionally specify a seed for deterministic deduplicaiton. Note that
# in Python 3.2.3 and higher, Dedupe also requires the PYTHONHASHSEED
# environment variable to be set to an integer for its results to be
# deterministic due to ordering dependencies.
seed: 0